<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var PartPayment $this */

use Resursbank\Ecom\Lib\Locale\Translator;
use Resursbank\Ecom\Module\PaymentMethod\Widget\PartPayment;

?>

<div class="rb-pp"">
    <?php // AJAX loading animation. ?>
    <div class="rb-pp-loader" style="display: none;">
        <div class="rb-pp-spinner">
            <svg class="rb-pp-circular" viewBox="25 25 50 50">
                <circle class="rb-pp-path" cx="50" cy="50" r="20" fill="none" stroke-width="5" stroke-miterlimit="10"/>
            </svg>
        </div>
    </div>

    <?php // Loader content overlay. ?>
    <div class="rb-pp-overlay" style="display: none;"></div>

    <?php // Content ?>
    <div class="rb-pp-content">
        <?php // Logo ?>
        <?php if ($this->logo !== ''): ?>
        <div class="rb-pp-logo-container"><?= $this->logo ?></div>
        <?php endif; ?>

        <?php // Pay in installments. ?>
        <?php if ($this->displayInfoText) : ?>
            <div class="rb-pp-info">
                <?= Translator::translate(phraseId: 'pay-in-installments-with-resurs-bank') ?>
            </div>
        <?php endif; ?>

        <?php // Starting at cost. ?>
        <?php $message = $this->getStartingAt() ?>
        <div class="rb-pp-starting-at">
            <?php if ($message !== ''): ?>
                <?= $message ?>
            <?php endif; ?>
        </div>

        <?php // Error message container. ?>
        <div class="rb-pp-error" style="display:none;"></div>
    </div>
</div>
